/* takumi_php - Auto-generated C header
 * Do not edit manually. Generated by cbindgen.
 */

#ifndef TAKUMI_PHP_H
#define TAKUMI_PHP_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle for a `GlobalContext` (font cache + persistent image store).
 */
typedef struct ContextHandle ContextHandle;

/**
 * Opaque handle for rendered image bytes ready to be read by PHP.
 */
typedef struct OutputHandle OutputHandle;

/**
 * Return a pointer to the last error message, or null if none.
 *
 * The pointer is valid until the next call that sets an error.
 */
const char *takumi_get_last_error(void);

/**
 * Clear the last error message.
 */
void takumi_clear_last_error(void);

/**
 * Create a new rendering context.
 *
 * The returned handle must be freed with `takumi_context_free`.
 * Reuse a context across multiple render calls to share font caches.
 */
struct ContextHandle *takumi_context_new(void);

/**
 * Free a context handle and release all associated resources.
 */
void takumi_context_free(struct ContextHandle *handle);

/**
 * Load a font from raw bytes into the context.
 *
 * - `data` / `data_len`: font file bytes (TTF, OTF, WOFF, WOFF2)
 * - `family`: override family name (null = auto-detect from font metadata)
 * - `weight`: override weight in 1–1000 (0 = auto-detect)
 * - `style`: override style string "normal" | "italic" | "oblique" (null = auto-detect)
 *
 * Returns 0 on success, -1 on error (call `takumi_get_last_error` for details).
 */
int takumi_context_load_font_data(struct ContextHandle *handle,
                                  const uint8_t *data,
                                  uintptr_t data_len,
                                  const char *family,
                                  int weight,
                                  const char *style);

/**
 * Load a font from a file path into the context.
 *
 * - `path`: null-terminated path to the font file
 * - `family` / `weight` / `style`: same semantics as `takumi_context_load_font_data`
 *
 * Returns 0 on success, -1 on error.
 */
int takumi_context_load_font_file(struct ContextHandle *handle,
                                  const char *path,
                                  const char *family,
                                  int weight,
                                  const char *style);

/**
 * Return a pointer to the rendered image bytes and write the length to `*out_len`.
 *
 * The pointer is valid until the handle is freed with `takumi_output_free`.
 */
const uint8_t *takumi_output_bytes(struct OutputHandle *handle, uintptr_t *out_len);

/**
 * Return the byte length of the rendered image.
 */
int64_t takumi_output_size(struct OutputHandle *handle);

/**
 * Save the rendered image to a file path. Returns 0 on success, -1 on error.
 */
int32_t takumi_output_save(struct OutputHandle *handle, const char *path);

/**
 * Free the output handle and its associated memory.
 */
void takumi_output_free(struct OutputHandle *handle);

/**
 * Render an HTML string to an image and return an output handle.
 *
 * - `ctx`: context holding loaded fonts; must remain valid until this call returns
 * - `html`: null-terminated HTML string
 * - `stylesheets` / `stylesheets_len`: array of CSS stylesheet strings to apply
 * - `width` / `height`: logical viewport dimensions in pixels
 * - `device_pixel_ratio`: output scale factor (1.0 = normal, 2.0 = HiDPI/2×).
 *   The output bitmap will be `width * dpr` × `height * dpr` pixels while CSS
 *   layout still happens at the logical dimensions.  Pass 0.0 to use 1.0.
 * - `format`: output format string "png" | "webp" | "jpeg" (null = "png")
 * - `quality`: JPEG/WebP quality 1–100 (0 = library default)
 *
 * Returns an `OutputHandle` on success, or null on error.
 * The caller must free the handle with `takumi_output_free`.
 */
struct OutputHandle *takumi_render_html(const struct ContextHandle *ctx,
                                        const char *html,
                                        const char *const *stylesheets,
                                        uintptr_t stylesheets_len,
                                        uint32_t width,
                                        uint32_t height,
                                        float device_pixel_ratio,
                                        const char *format,
                                        uint8_t quality);

#endif /* TAKUMI_PHP_H */
